### ISSUE TITLE
Not muting the volume when ad plays

### ISSUE THREAD

**Issue by gokulk16** [hm-arora/Jiocinema-ad-muter#2]
Have downloaded the installed the extension correctly, Also opened the pop-up and enabled from the jiocinema tab. Doesn't seem to mute anytime. 
Not while full-screen or not.
Can you please check?
I'm using Arc browser(Chromium-based which works for all chrome based extensions)

**Comment by gokulk16** [comment]
I'm assuming the extension will automatically detect and Mute ADs. Let me know if we have to do something to make the extension work.

**Comment by hm-arora** [comment]
Strange, it should work on Arc. I'll check and confirm.

**Comment by gokulk16** [comment]
Forked the repo and made some fixes here -> https://github.com/gokulk16/Ad-muter

This is working for me now. Thanks for source anyway 🙏
